request = REQLINE headers (* no body for now *)

<REQLINE> = method <SP> path [<SP> <PROTOCOL>] <CRLF> (* we can assume HTTP/1.1 *)

method = "GET"                                        (* incomplete, of course *)
path = "/"                                            (* obviously this needs to be expanded *)
SP = " "
CRLF = "\n"
PROTOCOL = "HTTP/1.1"

headers = {header} <CRLF>
header = NAME <": "> VALUE <CRLF>

NAME = #"[a-zA-Z\-]+"
VALUE = #"[^\n]*"
