REQUEST = REQLINE HEADERS (* no body for now *)

REQLINE = REQ_TYPE <SP> PATH [<SP> <PROTOCOL>] <CRLF> (* we can assume HTTP/1.1 *)

REQ_TYPE = "GET"                                    (* incomplete, of course *)
PATH = "/"                                          (* obviously this needs to be expanded *)
SP = " "
CRLF = "\n"
PROTOCOL = "HTTP/1.1"

HEADERS = {NAME <": "> VALUE <CRLF>} <CRLF>

NAME = #"[a-zA-Z\-]"
VALUE = #"[^\n]*"
